version: '3.9'
services:

  nginx:
    build: ./nginx/
    volumes:
      - ./www/html/:/var/www/html/
    restart: always
    links:
      - php
    ports:
      - 80:80
    container_name: nginx-container

  php:
    build: ./php/
    volumes:
      - ./www/html/:/var/www/html/
    restart: always
    expose:
      - 9000

  mysql:
    image: mysql:latest
    volumes:
      - /var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootdocker
      MYSQL_DATABASE: library
      MYSQL_USER: user
      MYSQL_PASSWORD: userdocker
    container_name: mysql-container